FROM jenkins/jenkins:lts
USER root

# Python and tools
RUN apt-get update && \
 apt-get install -y python3 python3-pip python3-venv && \
 apt-get clean

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# pytest and QA tools
RUN pip3 install --no-cache-dir \
 pytest pytest-html pytest-cov pytest-xdist \
 allure-pytest flake8 pylint mypy

# Jenkins Plugins
RUN jenkins-plugin-cli --plugins \
 git workflow-aggregator allure-jenkins-plugin \
 junit docker-workflow warnings-ng
USER jenkins
